kind: Template
apiVersion: v1
metadata:
  name: template-deploy-nginx
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    creationTimestamp: null
    labels:
      app: nginx
    name: nginx
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nginx
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx
      spec:
        containers:
        - image: nginx:1.12
          name: nginx
          resources: {}
